version: '3.3'

volumes:
  db-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME-local}
      - DB_USERNAME=${DB_USER-root}
      - DB_PASSWORD=${DB_PASSWORD-password}
      - "TZ=Asia/Tokyo"

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT-10000}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    platform: linux/x86_64
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME-local}
      MYSQL_USER: ${DB_USER-root}
      MYSQL_PASSWORD: ${DB_PASSWORD-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-password}
      TZ: 'Asia/Tokyo'
    volumes:
      - db-volume:/var/lib/mysql
